global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load alert rules
rule_files:
  - "rules/alerts.yml"

# Scrape configurations
scrape_configs:
  # Application metrics
  - job_name: 'moisture-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'moisture-api'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics

  # Node metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Remote write configuration for long-term storage
remote_write:
  - url: "http://victoria-metrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30

# Remote read configuration for historical data
remote_read:
  - url: "http://victoria-metrics:8428/api/v1/read"
    read_recent: true

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 15d
    retention.size: 50GB
    wal-compression: true

# Security configuration
basic_auth_users:
  admin: $2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewYpwBAM7RHqvHGS  # hashed password

# CORS configuration
cors:
  cors_origins:
    - https://grafana:3000
  cors_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS

# TLS configuration
tls_server_config:
  cert_file: /etc/prometheus/certs/server.crt
  key_file: /etc/prometheus/certs/server.key

# Exemplars configuration
exemplars:
  max_exemplars: 100000

# Tracing configuration
tracing:
  endpoint: "tempo:4317"
  sampling_fraction: 0.1
  insecure: true

# Query configuration
query:
  max_samples: 50000000
  timeout: 2m
  max_concurrent: 20
  lookback_delta: 5m

# Scrape configuration defaults
scrape_config_defaults:
  honor_labels: true
  honor_timestamps: true
  follow_redirects: true
  enable_http2: true

# Metric relabeling
metric_relabel_configs:
  - source_labels: [__name__]
    regex: 'go_.*'
    action: drop

  - source_labels: [__name__]
    regex: 'process_.*'
    action: drop

# Alert relabeling
alert_relabel_configs:
  - source_labels: [severity]
    regex: '^(critical|warning|info)$'
    action: keep

# Exemplar storage
exemplar_storage:
  max_exemplars: 100000

# Metadata storage
metadata_storage:
  retention: 120h
